### ISSUE TITLE
Assets Containment and Routes

### ISSUE THREAD

**Issue by johnkoht** [craigulliott/chicago_ideas#1]
Hey Craig,

Where are you defining the routes to your assets and resources. I see your using a custom asset-url(..., type) but I can't find how to add a new asset type for "fonts". I added a folder called fonts under app/assets but it's not able to locate it

**Comment by craigulliott** [comment]
Rails 3.1 uses an "asset pipeline" 

http://guides.rubyonrails.org/asset_pipeline.html

For custom fonts, can we just use type kit?   I have an account already setup.

**Comment by johnkoht** [comment]
Gotham font isn't on typekit. We can definitely switch to a similar font available on typekit. I'll have Patrick find one that matches the design. 

Thanks for info on assets pipeline.

**Comment by craigulliott** [comment]
Sounds good, thanks
