### ISSUE TITLE
Welcome email prints the urls for images instead of displaying images

### ISSUE THREAD

**Issue by jdoconnor** [craigulliott/chicago_ideas#62]
http://www.chicagoideas.com/assets/application/email_assets/logo-2c8bda3f67013b22b5fd762ee1f5961e.png
Hi Jay OConnor

Welcome to the Ideasphere! You’re account has been successfully created. You can access, modify or update your account at anytime by visiting http://www.chicagoideas.com/account

http://www.chicagoideas.com/assets/application/email_assets/footer-d22d3b218c34561a33f8af33b283fe7f.jpg

**Comment by craigulliott** [comment]
awesome!  thanks
