### ISSUE TITLE
when you delete a chapter, all performances should be deleted automatically

### ISSUE THREAD

**Issue by craigulliott** [craigulliott/chicago_ideas#7]

**Comment by jdoconnor** [comment]
If you want to do a deleted_at column for these, this should be done in code.  If you're ok doing a destructive delete, this can be done with a foreign key and the delete cascade in mysql (keeping the code clean)

**Comment by craigulliott** [comment]
is there some rails code that does this?

I thought it was something like:

has_many :performances, :dependent => :delete_all

**Comment by jdoconnor** [comment]
There is, but I know how you like being extra safe with the data and
putting validations in more than one place

On Sun, Feb 12, 2012 at 10:48 AM, Craig Ulliott <
reply@reply.github.com
